nasa/harmony-service-lib-py

- .github/release-drafter.yml
- .github/workflows/draft-release.yml
- .github/workflows/publish-release.yml
- .github/workflows/test.yml
- README.md
- makefile
- setup.py
A couple of notes:
1. After this change, by default, a release will be drafted / edited on merge.  It will summarize our changes using PR subjects, so we need to word them for use as release notes
2. Releases will automatically bump major/minor/patch versions.  By default, the patch version will be bumped.  If a PR needs a major or minor version bump, add the label "major" or "minor" to it accordingly.
3. Publication of releases to PyPI needs to be manual until I can set up tokens in our GitHub account.  I'm going to save this for later, so I can set up several other admin things all at once.  I'll comment out the actual publication for now and PR to restore it after it is set up.
> HARMONY-684: Setup GitHub actions for publication to PyPI with release notes

- harmony/util.py
- tests/test_util_download.py
This PR updates the `harmony.util._filename` function, so that if a user requests a URL with query parameters, those parameters aren't included in the file extension the downloaded output is saved to. For example:
```
https://opendap.earthdata.nasa.gov/this/is/my/file.dap.nc4?dap4.ce=variableOne
```
Right now, this gives the extension `.ce=variableOne`, instead of `.nc4`.
I did a quick check of how `urlparse` works with different URL types, and file paths, and found the following:
* `PurePath(parse.urlparse('https://opendap.earthdata.nasa.gov/this/is/my/file.dap.nc4?dap4.ce=variableOne').path).suffix` --> `'.nc4'`
* `PurePath(parse.urlparse('https://opendap.earthdata.nasa.gov/this/is/my/file.dap.nc4').path).suffix` --> `'.nc4'`
* …
> HARMONY-831 - Ensure a URL with query parameters is downloaded with the correct file extension

- harmony/http.py
- tests/test_http.py
This PR removes the URL encoding of the `data` dictionary that is given to `requests.post`. The `data` keyword argument is [expecting](https://docs.python-requests.org/en/master/user/quickstart/#more-complicated-post-requests) a regular dictionary or a string dump using `json.dumps`, rather than a URL encoded string.
The original intent behind the URL encoding was because OPeNDAP requires any constraint expression to be URL encoded (as variable paths can have slashes in them). This is better handled by encoding just the value of the constraint expression, rather than the whole data dictionary.
> DAS-1076: Remove URL encoding of POST query parameters.

- .github/workflows/publish-release.yml
- harmony/__init__.py
Successfully published v1.0.8 pointing to this branch:
https://github.com/nasa/harmony-service-lib-py/runs/2503228502?check_suite_focus=true
https://pypi.org/project/harmony-service-lib/1.0.8/
> HARMONY-833: Publish to PyPI when a release is published

- dev-requirements.txt
- harmony/http.py
- tests/test_http.py
This PR is trying to fix the out-of-memory error when processing some large granules from netcdf-to-zarr service.
It mainly addresses the memory issue during downloading step by using streaming request with optimized chunksize to balance download speed and memory consumption. The detailed experiments is summarized in the comment of JIRA story 838.
With this PR, the 1.8 GB benchmark from story-838 should be able to be processed with the current resource configuration in NGAP2 (4 GB instance type).
For local deployment, this benchmark would need at least 4.5 GB memory for docker configuration due to the memory overhead in localstack container.
> Harmony 838

- requirements.txt
This PR simply replace the version of python-json-logger by 2.0.1. I was trying to reproduce the warning message as mentioned in story https://bugs.earthdata.nasa.gov/browse/HARMONY-802, but don't see any, so it will be great if somebody can confirm with me about that.
> HARMONY-802: use python-json-logger 2.0.1 in requirements.txt

- example/example_message.json
- harmony/message.py
- tests/example_messages.py
- tests/test_message.py
HARMONY-1156
Supports the 0.15.0 of the data operation schema (added in HARMONY-1121) which adds coordinate variables and include type and subtype fields for variables.
There is not a service making use of these changes yet. Run the unit tests and make sure they pass. You could build a harmony-service-example with this updated library and then print out the message that gets passed in with:
http://localhost:3000/C1243747507-EEDTEST/ogc-api-coverages/1.0.0/collections/sea_surface_temperature/coverage/rangeset?subset=lat(-45%3A45)&subset=lon(0%3A180)&maxResults=1&format=image/png
to make sure the fields are parsed correctly. Note that the request will fail though (unrelated to the variables change).
> HARMONY-1156: Support 0.15.0 of the data operation schema - coordinate variables

- README.md
- dev-requirements.txt
- harmony/exceptions.py
- harmony/http.py
- harmony/util.py
- requirements.txt
- tests/test_http.py
- tests/test_util_download.py
- tests/util.py
HARMONY-1125
Automatically retries temporary request failures using https://urllib3.readthedocs.io/en/stable/reference/urllib3.util.html. 
Here is what the end result should look like on the Harmony side. (Note that I I also tweaked the way 500 download errors are handled as well by giving them a custom exception class so that we don't see the "unknown error" on the Harmony job.)
Checkout harmony-1125 in this repo and in the  Harmony repo. In harmony-service-lib-py activate your virtual environment and run `make install` to ensure the right version of responses is installed before running `make test`.
1. In harmony-service-lib-py in http.py at the top of the download function set `url='https://httpbin.org/status/502'`.
2. Build a service using your local copy of harmony-service-lib-py …
> Harmony 1125 - Automatically retry temporary request failures

- Makefile
- dev-requirements.txt
- setup.py
HARMONY-1125
Works around this issue https://github.com/pypa/twine/issues/726, https://peps.python.org/pep-0440/#direct-references:
> Public index servers SHOULD NOT allow the use of direct references in uploaded distributions. Direct references are 
> intended as a tool for software integrators rather than publishers.
https://bugs.earthdata.nasa.gov/browse/HARMONY-1188 was created to revert these changes once responses has a new release and the workaround is no longer needed.
With your virtual env activated:
run `make install`
run `make test`
The error https://github.com/nasa/harmony-service-lib-py/runs/6757666515?check_suite_focus=true#step:4:59 is not reproducible locally but the relevant failing command is:
`python -m twine upload --username "__token__" -*** --repository-url …
> HARMONY-1125: Work around twine upload issue

- Makefile
- harmony/exceptions.py
- harmony/http.py
- tests/test_http.py
- tests/test_util_download.py
HARMONY-1195
We've seen several different classes of errors including 400s and 500s where we want to retry the failure because it may succeed on a retry. The only cases where we definitely do not want to retry the same request are 401 and 403 errors.
We were seeing an issue with the way we were using the urllib Retry library to automatically retry HTTP errors because we'd see intermittent failures 3 redirects in verifying an authorization code with EDL. When that would fail we'd retry that specific redirect instead of the original URL, which was a problem because the EDL authorization codes are one time use only so that retry would always fail.
This changes the retries to happen a level up outside the HTTP urllib library, which allows those requests to succeed on a retry.
I also removed a …
> HARMONY-1195: Retry all file download error conditions except for authorization errors

- example/example_message.json
- harmony/message.py
- tests/example_messages.py
- tests/test_message.py
HARMONY-1191
This PR just updates the message object to handle the new fields (collection shortName, versionId) being passed to services from Harmony.
Build a service (like harmony-service-example) using this branch of the service lib and test it out (http://localhost:3000/C1233800302-EEDTEST/ogc-api-coverages/1.0.0/collections/all/coverage/rangeset?maxResults=2) with Harmony branch 1191. Log the source.shortName and source.versionId in your service's `process_item` method.
```
print(source)
print(source.versionId)
print(source.shortName)
```
> HARMONY-1191: Add short name and version id to message

- harmony/aws.py
- harmony/cli.py
- harmony/s3_stac_io.py
harmony-1247
When we transitioned from S3 to EFS I forgot to also modify the service lib to write the error message JSON files to S3. This change rectifies that oversight.
- check out this branch
- in transform.py proccess_item method of harmony-service-example add `raise HarmonyException('oh no')`
- `make build-image LOCAL_SVCLIB_DIR=../harmony-service-lib-py` in harmony-service-example
- restart services
- http://localhost:3000/C1233800302-EEDTEST/ogc-api-coverages/1.0.0/collections/all/coverage/rangeset?maxResults=2
- the job's error message should say 'oh no'
> HARMONY-1247: Write the error file to s3 if metadata dir is s3

- .github/workflows/test.yml
- dev-requirements.txt
- harmony/logging.py
HARMONY-1204
This fixes issues associated with service logging. Messages that should have shown up as JSON were showing up as text in Kibana, and were being duplicated.
This is because the root logger was always being used with 2 handlers (each of which can log the same message). The root logger already has a default handler attached to it and we were adding a subsequent custom handler. Therefore duplicate messages were being output as text+JSON (separated by /r/n) and were unable to be parsed as JSON.
(A logging handler doesn't always handle a log record if it is incompatible with its logic so sometimes only one of the handlers was being invoked (e.g. the custom JSON handler) and logs showed up just as expected, but this wasn't always the case.)
The least disruptive fix is to ensure that …
> Harmony 1204 - Fix service logging format

- .github/workflows/publish-release.yml
- .github/workflows/test.yml
- dev-requirements.txt
I made this branch harmony-784 so that it is linked to the similar dependency updates that I tacked onto https://github.com/nasa/harmony-py/pull/51/files, but I probably should have made this branch harmony-1188 ("Update harmony-service-lib-py responses dev dependency to an official release") as that is the ticket that is most related to this PR.
This just updates some pip and github action dev dependencies.
make install
make lint
make test
> Harmony 784, 1188 - Dependency updates (github actions, responses, flake8, pycodestyle)

- harmony/adapter.py
- harmony/cli.py
- harmony/s3_stac_io.py
- tests/test_cli_stac.py
HARMONY-1624
Allows service implementations to output multiple STAC catalogs. Formats/writes the STAC layout in a way that conforms to what Harmony already handles for existing services that do this without the service library (for services like Query CMR) -- e.g. catalog0.json, catalog1.json, batch-catalogs.json, batch-count.txt.
Run `make test`. If you want to test end to end:
1 - checkout this branch
2 - in harmony-service-example, checkout the ["test-multi-stac" branch](https://github.com/nasa/harmony-service-example/compare/test-multi-stac) and run `make build-image LOCAL_SVCLIB_DIR=../harmony-service-lib-py`
3 - add this to your harmony .env
```
HARMONY_SERVICE_EXAMPLE_SERVICE_QUEUE_URLS='["harmonyservices/service-example:test-multi-stac,http://localstack:4566/queue/harmony-service-e …
```
> Harmony 1624 - Allow service implementations to output multiple STAC catalogs

- .github/workflows/test.yml
- Makefile
- harmony/message_utility.py
- tests/test_message_utilities.py
These are Harmony Message utility functions that have been copied between services and seem to belong in this harmony-service-lib package. 
[DAS-1926](https://bugs.earthdata.nasa.gov/browse/DAS-1926)
This is a simplification / unification of duplicate code that exists in HyBIG and harmony-regridding-service, and I can see it being useful in other services.
This changes nothing to the existing library, just adds functionality that is related to Harmony Message objects, in particular Message.format.
Unit tests should pass with:
```
make test
```
* [ n/a ] Documentation updated (if needed)
> DAS-1926: Adds common Harmony Message functionality

- harmony/adapter.py
- harmony/http.py
- tests/test_util.py
Harmony-1719
Adds `A-api-request-uuid` query parameter to http/https download requests to support end-to-end tracking in Cloud Metrics
1. Checkout this branch
2. Clone the harmony-example-service repo
3. Build the service example image with this branch
```
make build-image LOCAL_SVCLIB_DIR=../harmony-service-lib-py
```
4. Start up harmony with `harmony-service-example` in `LOCALLY_DEPLOYED_SERVICES` in your .env file.
5. Tail the logs on the `harmony-service-example` pod.
6. Execute the following query
```
http://localhost:3000/C1233800302-EEDTEST/ogc-api-coverages/1.0.0/collections/red_var,blue_var,green_var/coverage/rangeset/?subset=lat(20%3A60)&subset=lon(-140%3A-50)&outputCrs=EPSG%3A31975&format=image%2Fpng&maxResults=1
```
7. Look for the download timing log entry in the service log …
> HARMONY-1719: Add request-id to download requests to support Cloud Metrics

- .github/workflows/publish-release.yml
- harmony/__init__.py
HARMONY-1756
Changes GitHub publish action to use trusted publisher token instead of password stored in GitHub secret.
1. Click on the 'Releases' link in the main page of this GitHub repo
2. Click on 'Draft release' button.
3. Create a dummy tag
4. Choose this branch instead of 'main'
5. Fill in title and description with whatever
6. Choose "pre-production release" checkbox 
7. Click on 'Publish release'
8. Check to the 'Actions' tab on the page and make sure the publish action succeeds
9. Go to pypi.org and search for `harmony-service-lib`
10. Check on the releases and verify that your release is there
11. Delete your test release
> Harmony 1756 - Use trusted publisher token to publish to PyPi

- harmony/cli.py
- tests/test_cli.py
HARMONY-1764
This change adds a new CLI parameter, --harmony-input-file, with which the data operation can be passed on the file system rather than as a command line parameter using --harmony-input. This is needed to support large data operations that were exceeding stack limits when passed using --harmony-input.
1. Check out this branch
2. Rebuild the trajectory-subsetter image using this branch of harmony-service-lib-py (need to chance requirements.txt)
3. Push the service to the harmony sandbox
4. Do a sandbox deployment including the service in LOCALLY_DEPLOYED_SERVICES
5. Run a query with a large number of variables
> Harmony 1764 add support for specifying data operation using a file

- Makefile
- dev-requirements.txt
- harmony/util.py
- pyproject.toml
- setup.py
- tests/test_util.py
HARMONY-1866
This work comes off the back of the net2cog production readiness check-in. net2cog currently needs custom code to determine the output file name for its reformatted products, because the common functionality in this library doesn't account for reformatting operations. This PR extends the existing `generate_output_filename` function to be able to add a `_reformatted` suffix when appropriate.
I'm totally open to a better choice of suffix. net2cog uses `_converted` for example, "Reformatting" matches with a lot of the terminology that's been floating around in our convergence meetings, so I think that's why I opted for that initially.
**CI/CD failures:**
Looks like the `safety` check is failing due to the version of `setuptools` used. I looked a bit more into that, and it can be …
> HARMONY-1866 - Enable _reformatted prefix in output file names.

- example/example_message.json
- harmony_service_lib/message.py
- requirements.txt
- tests/example_messages.py
- tests/test_message.py
HARMONY-1912
Adds support for the average parameter which specifies the averaging method to use for averaging services. This will be for the Giovanni services to know whether the request is for 'time' or 'area' averaging.
Test with the main harmony repo changes.
> HARMONY-1912: Add support for the average parameter which specifies the averaging method to use for averaging services

- harmony_service_lib/adapter.py
- requirements.txt
- tests/test_adapter_stac.py
HARMONY-1922
the STAC spec requires a geometry if a STAC item has a bbox. This is now enforced by pystac. This change adds the
geometry field by creating a Polygon to match the bbox if there is a bbox, but not a geometry defined for the STAC item.
1. Run `make test`
2. Rebuild the `harmony-service-example` service image with this branch and deploy to your local environment. Verify that queries still work
> HARMONY-1922: Add geometry to STAC item  when bbox is defined, but geometry is not

- README.md
- harmony_service_lib/http.py
- harmony_service_lib/util.py
- tests/test_util.py
- tests/util.py
HARMONY-1928
Add support of long url download via POST
Changed a locally deployed service built with the local version of this branch to download a long Opendap url, verify the download is done via POST and is successful. Verify other requests still succeed.
> HARMONY-1928: Add support of long url download via POST

- README.md
- harmony_service_lib/earthdata.py
- harmony_service_lib/http.py
- harmony_service_lib/util.py
- tests/test_earthdata.py
- tests/test_http.py
- tests/util.py
HARMONY-1938
In order to support local Harmony development without requiring an Earthdata Login application we needed to make some changes to no longer require OAUTH* environment variables with the EDL app information. As part of that change we're also removing the FALLBACK_AUTHN_ENABLED functionality that has not been used for the past few years which required an EDL client application in order to authenticate using a username and password.
Test along with the harmony-1938 branch in the main harmony repo. Make sure that services start correctly when OAUTH* environment variables are not set, and the services can continue to successfully download data.
I used this branch for building the opera-rtc-s1-browse image - https://github.com/chris-durbin/opera-rtc-s1-browse/tree/use-local-harmony-s …
> HARMONY-1938: Remove fallback authentication functionality and related code

- harmony_service_lib/earthdata.py
- tests/test_earthdata.py
HARMONY-1938
The latest service library changes were not working when attempting to download a file that resulted in a redirect to a pre-signed S3 URL. The issue was that the Authorization header with the EDL bearer token was being sent to the redirect location which had conflicting query parameters (Signature and X-Amz-Algorithm indicate a different authorization method).
Now the library will pass in the Authorization header unless one of those query parameters is present in the request.
This cannot be tested locally - it needs to be tested in an AWS environment.
1. Build the harmony-service-example service using the service library in this branch.
2. Push the image to your sandbox (use a tag other than latest so that it does not conflict with the image used for the main sandbox).
3. …
> HARMONY-1938: Update code to omit Authorization header when redirected to a presigned S3 URL

- harmony_service_lib/cli.py
- harmony_service_lib/exceptions.py
- tests/test_cli_stac.py
HARMONY-1983
Here is a description of the full NoData/EmptyResult error handling workflow from the beginning to the end:
1) Service implementer throws NoDataException in service code when NoData/EmptyResult error is encountered.
2) harmony-service-lib-py defines the new NoDataException and catches it when it is thrown from the service invocation. It saves the NoDataException as a warning in the error.json file for the work item service invocation.
3) Harmony service-runner reads the error.json file when detecting the service call failed, then construct the workitem with the warning info and call the backend work item update endpoint to update the work item.
4) Harmony backend saves the workitem in database with a 'warning' status and save the warning info into `job_errors` table which has …
> HARMONY-1983: As a service provider I want the service library to provide a way of indicating an empty result.

- harmony_service_lib/http.py
HARMONY-1972
Improve the error message when trying to read a response from an HTTP file download when the connection to the download site is dropped.
Note that I do not have a reliable way to reproduce the issue from the ticket. This will at a minimum ensure that we don't return the message to the end user: "AttributeError: 'NoneType' object has no attribute 'ok'".
Build the harmony service example using this branch and submit a request to sanity check downloads still work as expected.
> HARMONY-1972: Prevent exception when trying to read a response from an HTTP file download.

- example/example_message.json
- harmony_service_lib/message.py
- tests/example_messages.py
- tests/test_message.py
HARMONY-1965
Add pixelSubset to data operation schema 0.21.0
Follow instructions in Harmony PR: https://github.com/nasa/harmony/pull/703 to test.
> HARMONY-1965: Add pixelSubset to data operation schema 0.21.0

- dev-requirements.txt
- harmony_service_lib/provenance.py
- tests/test_provenance.py
TRT-42 (centralising some functionality to support the intent of that feature)
This PR adds a fairly simplistic function to create a correctly formatted `history` attribute string, with a view to centralising that functionality for Harmony services.
The function tries to stay agnostic to both the file format where the metadata attribute either comes from or is to be written, and to the packages used to by specific services to interact with those file formats (e.g., `xarray` versus `netCDF4` versus `h5py`, etc). That severely limits the scope of the function and is what makes it very lightweight.
Right now the `provenance.py` module has only one function in it, but in the future `history_json` creation could/should also be added here. Having this module at least gives us a location to …
> TRT-42: Add function to create history metadata attribute.

- harmony_service_lib/message_utility.py
- tests/test_message_utilities.py
TRT-572 (small supporting work)
This PR updates the `has_self_consistent_grid` function to add an optional argument stating whether the message is valid if there are no grid parameters defined. This value is returned in the final case, when there are none of:
* `format.scaleExtent`
* `format.scaleSize`
* `format.height` _and_ `format.width`
The default value of this new argument is `False`, which preserves prior behaviour.
This change supports use-cases for the Harmony Regridding Service (particularly via EDSC), when an end-user may specify a projection, but no grid parameters. Indeed, EDSC does not allow users to provide grid parameters at this point.
* Pull this branch.
* Define an empty Harmony message.
* Call this function using that empty message, without defining `valid_if_no_grid` …
> TRT-572: Update grid self-consistency validation.

- harmony_service_lib/message_utility.py
- tests/test_message_utilities.py
TRT-572 (again, ish)
Updates new named argument from `valid_if_no_grid` to `allow_incomplete_grid` for improved accuracy. Apologies for merging #61 before seeing the suggestions from @flamingbear.
* As before: run the tests locally under Python 3.9 or 3.10 and Python 3.11+.
* ~~Acceptance criteria met~~
* ~~Documentation updated (if needed)~~
> TRT-572: Rename to allow_incomplete_grid.

- .github/CODEOWNERS
HARMONY-2077
Add CODEOWNERS file to make github auto-add reviewers to PRs
None
> HARMONY-2077: Add CODEOWNERS file to make github auto-add reviewers to PRs

- README.md
- harmony_service_lib/exceptions.py
- tests/test_cli_stac.py
HARMONY-2159
Add NoRetryException to support services returning non-retriable errors.
make install
> HARMONY-2159: Add NoRetryException to support services returning non-retriable errors.

- harmony_service_lib/exceptions.py
- tests/test_exceptions.py
ostensibly DAS-2373, but I just found my exceptions weren't working as expected in my tests so here's a PR to fix that.
~I'm not 100% sure this is generally acceptable behavior.~. I'm pretty sure since HarmonyException defines it's own `__init__` function, we should call the parent's constructor directly.
Harmony's base custom extension calls the parent constructor with a message.
Pull this branch, run the tests 
```
❯ make install && make lint && make test
```
You can revert the change in the source to see the second test fail if you're feeling up to it.
> DAS-2373: Call Exception(message) for Harmony exceptions.
